repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run PyTest
        entry: pytest
        language: system
        types: [python]
        stages: [pre-commit, pre-push]
        args: ["tests/"]
      - id: commit-msg
        name: Commit Message Check
        entry: scripts/hooks/commit-msg-check.sh
        language: script
        stages: [commit-msg]
      - id: restricted-file-check
        name: Restricted File and Section Check
        entry: scripts/hooks/restricted-file-check.sh
        language: script
        stages: [pre-commit]
      - id: filename-check
        name: Filename Snake Case Check
        entry: scripts/hooks/filename-check.sh
        language: script
        stages: [pre-commit]
      - id: generate-docs
        name: Generate Documentation
        entry: scripts/hooks/generate_docs.sh
        language: script
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
      - id: branch-name-check
        name: Branch Name Check
        entry: scripts/hooks/branch-name-check.sh
        language: script
        stages: [post-checkout]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        name: ruff-linter
        types_or: [python, pyi, jupyter]
        args: ["--config=pyproject.toml", "--fix", "--preview"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        name: black-formatter
        language_version: python3.10
      - id: black-jupyter
        name: black-jupyter-formatter
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: docs/api-reference.md
      - id: end-of-file-fixer
        exclude: docs/api-reference.md
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        types: [yaml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          - --config-file=pyproject.toml
