name: Black Code Formatter

on:
  push:
    paths:
      - 'src/**/*.py'
      - 'notebooks/**/*.ipynb'
      - 'tests/**/*.py'
  pull_request:
    paths:
      - 'src/**/*.py'
      - 'notebooks/**/*.ipynb'
      - 'tests/**/*.py'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Black with Jupyter support
      run: pip install black[jupyter]==23.7.0

    - name: Auto-format Python and Jupyter Notebook files
      run: |
        echo "Formatting .py and .ipynb files in src/, notebooks/, and tests/"
        find src/ notebooks/ tests/ -type f \( -name "*.py" -o -name "*.ipynb" \) -exec black {} +

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v8
      with:
        message: 'Apply Black formatting'
        add: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}